# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |                          Azure Load Balancer Validation                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: {{ item.name | default('') }} - Azure LB Validation"
  run_once:                             true
  block:
    - name:                             "Test Setup: {{ item.name | default('') }} - Initialize Test Case"
      ansible.builtin.include_tasks:    "roles/misc/tasks/test-case-setup.yml"
      tags:                             [pre-validation]

    - name:                             "Test Execution: {{ item.name | default('') }} - Validate Azure Load Balancer Config"
      become:                           true
      block:
        - name:                         "Test Execution: {{ item.name | default('') }} - Retrieve Azure Instance Metadata"
          ansible.builtin.uri:
            url:                        http://169.254.169.254/metadata/instance?api-version=2021-02-01
            use_proxy:                  false
            headers:
              Metadata:                 true
          register:                     azure_instance_metadata

        - name:                         "Test Execution: {{ item.name | default('') }} - Get Azure Load Balancer IP"
          ansible.builtin.uri:
            url:                        http://169.254.169.254:80/metadata/loadbalancer?api-version=2020-10-01
            use_proxy:                  false
            headers:
              Metadata:                 true
          register:                     azure_loadbalancer_metadata

        - name:                         "Test Execution: {{ item.name | default('') }} - Check Azure Load Balancer"
          delegate_to:                  localhost
          get_azure_lb:
            subscription_id:            "{{ azure_instance_metadata.json.compute.subscriptionId }}"
            region:                     "{{ azure_instance_metadata.json.compute.location }}"
            inbound_rules:              "{{ azure_loadbalancer_metadata.json.loadbalancer.inboundRules }}"
            constants:                  "{{ all_constants }}"
            msi_client_id:              "{{ user_assigned_identity_client_id | default('') }}"
          register:                     test_result

        - name:                         "Post Validation: {{ item.name | default('') }} - Set Test Case Status"
          ansible.builtin.set_fact:
            test_case_name:             "{{ item.name | default('') }}: {{ virtual_host }}"
            test_case_message:          "{{ test_result.message }}"
            test_case_details:          "{{ test_result.details }}"
            test_case_hostname:         "{{ virtual_host }}"
            test_case_status:           "{{ test_result.status }}"

      rescue:
        - name:                         "Rescue: {{ item.name | default('') }} - Set Test Case Failure"
          ansible.builtin.set_fact:
              test_case_name:           "{{ item.name | default('') }}: {{ virtual_host }}"
              test_case_status:         "FAILED"
              test_case_details:        "{{ test_result }}"
              test_case_message:        "{{ ansible_failed_result }}"
              test_case_hostname:       "{{ virtual_host }}"

    - name:                             "Telemetry: {{ item.name | default('') }} - Send Telemetry Data"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-telemetry-data.yml"
      tags:                             [telemetry]
