# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------|
# |            Pre Validation Tasks for ASCS/ERS Tests                         |
# /*---------------------------------------------------------------------------|

- name:                             "Pre Validation: ASCS Nodes"
  when:                             node_tier == "scs" or node_tier == "ers"
  block:
    - name:                         "Pre Validation: Validate SCS cluster status on ASCS node"
      get_cluster_status_scs:
        sap_sid:                    "{{ sap_sid | lower }}"
        ansible_os_family:          "{{ ansible_os_family | upper }}"
      become:                       true
      register:                     cluster_status_pre

    - name:                         "Pre Validation: CleanUp any failed resource"
      become:                       true
      ansible.builtin.command:      crm_resource --cleanup
      ignore_errors:                true
      register:                     cleanup_failed_resource_pre
      timeout:                      "{{ default_timeout }}"
      retries:                      3
      until:                        cleanup_failed_resource_pre.rc == 0
      changed_when:                 cleanup_failed_resource_pre.rc == 0
      failed_when:                  cleanup_failed_resource_pre.rc != 0

    - name:                         "Pre Validation: Set default pre Validation status as false"
      ansible.builtin.set_fact:
        pre_validations_status:     "FAILED"

    - name:                         "Pre Validation: Set pre Validation status"
      when:
                                    - cluster_status_pre is defined
                                    - cluster_status_pre.ascs_node != "" and
                                      cluster_status_pre.ers_node != ""
                                    - cluster_status_pre.pacemaker_status == "running"
      ansible.builtin.set_fact:
        pre_validations_status:     "PASSED"
