# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

####################################################################################
#                     Render HTML report from the test results                     #
####################################################################################

- name:                                 "Report: Create HTML Report"
  run_once:                             true
  delegate_to:                          localhost
  block:
    - name:                             "Report: Load HTML Template"
      no_log:                           true
      ansible.builtin.set_fact:
        html_report_template:           "{{ lookup('file', html_template_name | default('./templates/report.html')) }}"

    - name:                             "Report: Get Framework Version"
      no_log:                           true
      ansible.builtin.set_fact:
        framework_version:              "{{ lookup('file', playbook_dir + '/../VERSION', errors='ignore') | default('unknown') }}"

    - name:                             "Report: Resolve Execution Log Path"
      ansible.builtin.set_fact:
        _execution_log_path:            "{{ execution_log_path
                                            | default(
                                                lookup('env', 'ANSIBLE_LOG_PATH')
                                                | default('', true),
                                              true)
                                          }}"

    - name:                             "Report: Render HTML Report"
      render_html_report:
        test_group_invocation_id:       "{{ test_group_invocation_id }}"
        test_group_name:                "{{
                                          report_file_name
                                          | default(
                                              (
                                                (test_group_name
                                                 if (test_group_name is defined)
                                                 else 'TESTS')
                                                ~ '_'
                                                ~ (
                                                  (target_os_family
                                                   if (target_os_family is defined)
                                                   else (
                                                     (ansible_os_family
                                                      if (ansible_os_family is defined)
                                                      else 'UNKNOWN')
                                                   ))
                                                  | upper
                                                )
                                              )
                                          )
                                        }}"
        report_template:                "{{ html_report_template }}"
        workspace_directory:            "{{ _workspace_directory }}"
        test_case_results:              "{{ all_results | default([]) }}"
        system_info:                    "{{ system_info | default({}) }}"
        framework_version:              "{{ framework_version | default('unknown') }}"
        execution_log_path:             "{{ _execution_log_path }}"
      register:                         report_file_path
