# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Description: This file contains the expected configuration for the pacemaker cluster. The values
# are based on Microsoft's best practices and are subject to change based on the customer's requirements.

# === CRM Configuration Defaults ===
# cibadmin --query --scope crm_config
CRM_CONFIG_DEFAULTS:
  cluster-infrastructure:             corosync
  priority-fencing-delay:             '30'
  stonith-action:                     reboot
  stonith-enabled:                    'false'
  concurrent-fencing:                 'true'
  maintenance-mode:                   'false'
  node-health-strategy:               'custom'
  azure-events-az_globalPullState:    'IDLE'

# === Operation Defaults ===
# cibadmin --query --scope op_defaults
OP_DEFAULTS:
  record-pending:                     'true'
  timeout:                            '600'

# === Resource Defaults ===
# cibadmin --query --scope rsc_defaults
RSC_DEFAULTS:
  migration-threshold:                '3'
  priority:                           '1'
  resource-stickiness:                '1'

# === Constraints ===
# cibadmin --query --scope constraints
CONSTRAINTS:
  rsc_colocation:
    score:                            "-5000"
    rsc-role:                         "Started"
    with-rsc-role:                    "Started"

  rsc_order:
    first-action:                     "start"
    then-action:                      "stop"
    symmetrical:                      "false"

  rsc_location:
    score-attribute:                  "#health-azure"
    operation:                        "defined"
    attribute:                        "#uname"

# === Valid Configurations for different OS versions ===
# Specify the properties that are different for different OS versions
VALID_CONFIGS:
  REDHAT:
    priority-fencing-delay:           '15s'
  SUSE: {}
  AFA:
    have-watchdog:                    "false"
    stonith-timeout:                  "900"
  ISCSI:
    have-watchdog:                    "true"
    stonith-timeout:                  "144s"

# === Resource Defaults ===
# cibadmin --query --scope resources
RESOURCE_DEFAULTS:
  SUSE:
    stonith:
      instance_attributes:
        pcmk_delay_max:                   "15"
        pcmk_monitor_retries:             "4"
        pcmk_action_limit:                "3"
        pcmk_reboot_timeout:              "900"
        power_timeout:                    "240"
      operations:
        monitor:
          interval:                         "3600"
          timeout:                          "120"
        start:
          interval:                         "0"
          timeout:                          "20"
        stop:
          interval:                         "0"
          timeout:                          "20"

    ascs:
      instance_attributes:
        AUTOMATIC_RECOVER:                "false"
        MINIMAL_PROBE:                    "true"
      meta_attributes:
        resource-stickiness:              "5000"
        priority:                         "100"
      operations:
        monitor:
          interval:                       "11"
          timeout:                        "60"
        start:
          interval:                       "0"
          timeout:                        "180"
        stop:
          interval:                       "0"
          timeout:                        "240"
        promote:
          interval:                       "0"
          timeout:                        "320"
        demote:
          interval:                       "0"
          timeout:                        "320"

    ers:
      instance_attributes:
        AUTOMATIC_RECOVER:                "false"
        MINIMAL_PROBE:                    "true"
        IS_ERS:                           "true"
      meta_attributes:
        resource-stickiness:              "5000"
        priority:                         "100"
      operations:
        monitor:
          interval:                       "11"
          timeout:                        "60"
        start:
          interval:                       "0"
          timeout:                        "180"
        stop:
          interval:                       "0"
          timeout:                        "240"
        promote:
          interval:                       "0"
          timeout:                        "320"
        demote:
          interval:                       "0"
          timeout:                        "320"

    ipaddr:
      meta_attributes:
        target-role:                      "Started"
      operations:
        monitor:
          interval:                       "10"
          timeout:                        "20"
        start:
          interval:                       "0"
          timeout:                        "20"
        stop:
          interval:                       "0"
          timeout:                        "20"

    azurelb:
      meta_attributes:
        resource-stickiness:              "0"
      operations:
        monitor:
          interval:                       "10"
          timeout:                        "20"
        start:
          interval:                       "0"
          timeout:                        "20"
        stop:
          interval:                       "0"
          timeout:                        "20"

    azureevents:
      meta_attributes:
        allow-unhealthy-nodes:            "true"
        failure-timeout:                  "120s"
      operations:
        monitor:
          interval:                       "10"
          timeout:                        "240"
        start:
          interval:                       "0"
          timeout:                        "10"
        stop:
          interval:                       "0"
          timeout:                        "10"

# === OS Parameters ===
# Run command as root. Format of command is: "parent_key child_key"
# Example: sysctl net.ipv4.tcp_timestamps
OS_PARAMETERS:
  DEFAULTS:
    sysctl:
      net.ipv4.tcp_timestamps:          "net.ipv4.tcp_timestamps = 0"
      vm.swappiness:                    "vm.swappiness = 60"
    corosync-cmapctl:
      runtime.config.totem.token:       "runtime.config.totem.token (u32) = 30000"
      runtime.config.totem.consensus:   "runtime.config.totem.consensus (u32) = 36000"

# === Azure Load Balancer ===
# Azure Load Balancer configuration
AZURE_LOADBALANCER:
  PROBES:
    probe_threshold:                    2
    interval_in_seconds:                5
    number_of_probes:                   2

  RULES:
    idle_timeout_in_minutes:            30
    enable_floating_ip:                 true
    enable_tcp_reset:                   false
