# Enumeration definitions
enums:
  severity:
    - info:                           &info "INFO"
    - high:                           &high "HIGH"
    - low:                            &low "LOW"
    - warning:                        &warning "WARNING"
    - critical:                       &critical "CRITICAL"
    - all_severity:                   &severity [*info, *high, *low, *warning, *critical]

  os_type:
    - suse:                           &suse "SUSE"
    - redhat:                         &redhat "REDHAT"
    - oraclelinux:                    &oraclelinux "OracleLinux"
    - windows:                        &windows "Windows"
    - all_os:                         &os_type [*suse, *redhat, *oraclelinux, *windows]

  os_version:
    - suse_12_3:                      &suse_12_3 "SUSE 12 SP3"
    - suse_12_4:                      &suse_12_4 "SUSE 12 SP4"
    - suse_12_5:                      &suse_12_5 "SUSE 12 SP5"
    - all_versions:                   &all_versions "all"

  hardware_type:
    - vm:                             &vm "VM"
    - hli:                            &hli "HLI"
    - all_hardware:                   &all_hardware [*vm, *hli]

  storage_type:
    premium_storage:                  &premium_storage ["Premium_LRS","UltraSSD_LRS","ANF","PremiumV2_LRS"]
    anf:                              &anf ["ANF"]

  workload:
    - sap:                            &sap "SAP"
    - all_workload:                   &workload [*sap]

  db:
    - hana:                           &hana "HANA"
    - mssql:                          &mssql "MSSQL"
    - oracle:                         &oracle "Oracle"
    - db2:                            &db2 "Db2"
    - ase:                            &ase "ASE"
    - all_db:                         &db [*hana, *mssql, *oracle, *db2, *ase]

  role:
    - db:                             &db_role "DB"
    - ascs:                           &ascs_role "SCS"
    - ers:                            &ers_role "ERS"
    - app:                            &app_role "APP"
    - webdispatcher:                  &web_dispatch "WEB"
    - pas:                            &pas "PAS"
    - all_role:                       &role [*db_role, *ascs_role, *ers_role, *app_role, *web_dispatch, *pas]

  cluster_type:
    - sbd:                            &sbd "ISCSI"
    - fencing_agent:                  &fencing_agent "AFA"
    - all_fencing_agent:              &cluster_type [*sbd, *fencing_agent]

  collector_type:
    - command:                        &command "command"
    - azure:                          &azure "azure"
    - all_collector_type:             &collector_type [*command, *azure]

  category:
    - package:                        &package_check "Package"
    - vm:                             &vm_check "Virtual Machine"
    - sap:                            &sap_check "SAP"
    - os:                             &os_check "Operating System"
    - all_check_types:                &category [*package_check, *vm_check, *sap_check, *os_check]

  user:
    - root:                           &root "root"
    - sidadm:                         &sidadm "sidadm"
    - all_users:                      &user [*root, *sidadm]

  validator_type:
    - string:                         &string "string"
    - range:                          &range "range"
    - list:                           &list "list"
    - all:                            &validator_type [*string, *range, *list]

  report:
    - check:                          &check "check"
    - section:                        &section "section"
    - report:                         &report [*check, *section]


# Check definitions
checks:
  - id:                               "IC-0001"
    name:                             "Hostname"
    description:                      "Checks the hostname of the system on Linux"
    category:                         *vm_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat, *oraclelinux]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           *role
      database_type:                  *db
    collector_type:                   *command
    collector_args:
      command:                        "/bin/hostname"
      user:                           *root
    report:                           *check

  - id:                               "IC-0002"
    name:                             "Hostname"
    description:                      "Checks the hostname of the system on Windows"
    category:                         *vm_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        *windows
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           *role
      database_type:                  *db
    collector_type:                   *command
    collector_args:
      command:                        "hostname"
      user:                           *root
    report:                           *check

  - id:                               "IC-0003"
    name:                             "Hosts"
    description:                      "Checks the hosts file on Linux"
    category:                         *vm_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat, *oraclelinux]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           *role
      database_type:                  *db
    collector_type:                   *command
    collector_args:
      command:                        "/bin/cat /etc/hosts"
      user:                           *root
    report:                           *section

  - id:                               "IC-0023"
    name:                             "SrHook Configuration"
    description:                      "Checks the SrHook configuration of the system"
    category:                         *sap_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           [*db_role]
      database_type:                  [*hana]
    collector_type:                   *command
    collector_args:
      command:                        "/bin/cat /etc/sudoers.d/20-saphana"
      user:                           *root
    report:                           *section

  - id:                               "IC-0024"
    name:                             "HADR Dump"
    description:                      "Checks the HADR Dump of the system"
    category:                         *sap_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           [*db_role]
      database_type:                  [*db2]
    collector_type:                   *command
    collector_args:
      command:                        "db2pd -alldbs -hadr"
      user:                           *sidadm
    report:                           *section

  - id:                               "IC-0025"
    name:                             "Microsoft Defender Exclusion List"
    description:                      "Checks the Microsoft Defender Exclusion List"
    category:                         *vm_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat, *oraclelinux]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           [*db_role, *ascs_role, *app_role]
      database_type:                  [*hana, *ase, *db2, *oracle]
    collector_type:                   *command
    collector_args:
      command:                        "/bin/mdatp exclusion list"
      user:                           *root
    report:                           *section

  - id:                               "IC-0026"
    name:                             "Kernel Version"
    description:                      "Checks the kernel version of the system"
    category:                         *vm_check
    severity:                         *info
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat, *oraclelinux]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           *role
      database_type:                  *db
    collector_type:                   *command
    collector_args:
      command:                        "/bin/uname -r"
      user:                           *root
    report:                           *check
