# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------
# |                     Kill Enqueue Replication Server Process               |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup: {{ item.name | default('') }} - Initialize Test Case"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true
  tags:                                 [pre-validation]

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validation: {{ item.name | default('') }} - SCS Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-scs.yml"
  tags:                                 [pre-validation]

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: {{ item.name | default('') }} - Kill Enqueue Replication Server Process"
  become:                               true
  when:                                 pre_validations_status == "PASSED"
  tags:                                 [test-execution]
  block:
    - name:                             "Test Execution: {{ item.name | default('') }} - Kill Enqueue Replication Server on ERS Node"
      when:                             ansible_hostname == cluster_status_pre.ers_node
      become:                           true
      tags:                             [test-execution]
      block:
        - name:                         "Test Execution: {{ item.name | default('') }} - Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ hostvars[cluster_status_pre.ers_node].ansible_hostname }}"

        - name:                         "Test Execution: {{ item.name | default('') }} - Check for ENSA version"
          ansible.builtin.shell:        pgrep -f 'enqr.sap{{ sap_sid | upper }}'
          register:                     ensa2_check
          failed_when:                  false

        - name:                         "Test Execution: {{ item.name | default('') }} - Kill Enqueue Replication Server Process (ENSA1)"
          when:                         ensa2_check.stdout == ""
          ansible.builtin.shell:        set -o pipefail && pgrep -f 'er.sap{{ sap_sid | upper }}' | xargs kill -9
          register:                     kill_er_result
          failed_when:                  false

        - name:                         "Test Execution: {{ item.name | default('') }} - Kill Enqueue Replication Server Process (ENSA2)"
          when:                         ensa2_check.stdout != ""
          ansible.builtin.shell:        set -o pipefail && pgrep -f 'enqr.sap{{ sap_sid | upper }}' | xargs kill -9
          register:                     kill_enqr_result
          failed_when:                  false

        - name:                         "Test Execution: {{ item.name | default('') }} - Validate ERS node is not running"
          get_cluster_status_scs:
            sap_sid:                    "{{ sap_sid | lower }}"
          register:                     cluster_status_test_execution_pre
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until:                        cluster_status_test_execution_pre.ers_node == ""

        - name:                         "Test Execution: {{ item.name | default('') }} - Cleanup resources"
          ansible.builtin.command:      crm_resource --cleanup
          register:                     cleanup_failed_resource_test_execution
          changed_when:                 cleanup_failed_resource_test_execution.rc == 0

        - name:                         "Test Execution: {{ item.name | default('') }} - Validate SCS cluster status"
          get_cluster_status_scs:
            sap_sid:                    "{{ sap_sid | lower }}"
          register:                     cluster_status_test_execution
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        cluster_status_test_execution.ascs_node == cluster_status_pre.ascs_node
                                        and cluster_status_test_execution.ers_node == cluster_status_pre.ers_node

        - name:                         "Test Execution: {{ item.name | default('') }} - Determine test execution status"
          ansible.builtin.set_fact:
            test_execution_status:      "{{ 'PASSED' if (
                                            cluster_status_test_execution.ascs_node == cluster_status_pre.ascs_node and
                                            cluster_status_test_execution.ers_node == cluster_status_pre.ers_node
                                          ) else 'FAILED' }}"

        - name:                         "Test Execution: {{ item.name | default('') }} - Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Report: {{ item.name | default('') }} - Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: |
                                        ENSA Version: {{ "ENSA1" if ensa2_check.stdout == "" else "ENSA2" }}
                                        ASCS Node: {{ cluster_status_pre.ascs_node }}
                                        ERS Node: {{ cluster_status_pre.ers_node }}
            test_case_details_from_test_case: {
                                        "Pre Validations: Validate SCS cluster status": "{{ cluster_status_pre }}",
                                        "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre | default('Not Executed') }}",
                                        "Test Execution: ENSA Version Check": "{{ ensa2_check }}",
                                        "Test Execution: Kill Enqueue Replication Server Process (ENSA1)": "{{ kill_er_result | default(omit) }}",
                                        "Test Execution: Kill Enqueue Replication Server Process (ENSA2)": "{{ kill_enqr_result | default(omit) }}",
                                        "Test Execution: Cleanup resources": "{{ cleanup_failed_resource_test_execution }}",
                                        "Post Validations Result": "{{ cluster_status_test_execution }}",
                                        }

    - name:                             "Post Validation: {{ item.name | default('') }} - Consolidate ERS Results"
      when:                             ansible_hostname == cluster_status_pre.ascs_node
      ansible.builtin.set_fact:
        test_execution_start:           "{{ hostvars[cluster_status_pre.ers_node].test_execution_start | default('') }}"
        test_execution_end:             "{{ hostvars[cluster_status_pre.ers_node].test_execution_end | default('') }}"
        test_execution_hostname:        "{{ hostvars[cluster_status_pre.ers_node].test_execution_hostname | default(cluster_status_pre.ers_node) }}"
        test_execution_status:          "{{ hostvars[cluster_status_pre.ers_node].test_execution_status | default('FAILED', true) }}"
        test_case_message_from_test_case: "{{ hostvars[cluster_status_pre.ers_node].test_case_message_from_test_case | default('Test execution status not set - possible execution failure', true) }}"
        test_case_details_from_test_case: "{{ hostvars[cluster_status_pre.ers_node].test_case_details_from_test_case | default({}) }}"
# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validation: {{ item.name | default('') }} - Validate Results"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
      tags:                             [post-validation]

  rescue:
    - name:                             "Rescue: {{ item.name | default('') }} - Handle Failure"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"
      tags:                             [cleanup]

- name:                                 "Pre Validation: {{ item.name | default('') }} - Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Report: {{ item.name | default('') }} - Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for SCS cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Validate SCS cluster status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validation: {{ item.name | default('') }} - Validate Results"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
      tags:                             [post-validation]
