# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |                          Freeze File System on Primary Node                |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  when:                                 NFS_provider == "ANF"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: HANA DB Nodes"
  when:                                 NFS_provider == "ANF"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/

- name:                                 "Test Execution: Freeze File System on Primary Node init"
  become:                               true
  when:
                                        - node_tier == "hana"
                                        - NFS_provider == "ANF"
                                        - pre_validations_status == "PASSED"
                                        - cluster_status_pre.stonith_action == "reboot"
  block:
    - name:                             "Test Execution: Freeze File System on Primary Node init"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ ansible_hostname }}"

        - name:                         "Test Execution: Freeze the file system"
          become:                       true
          filesystem_freeze:
            nfs_provider:               "{{ NFS_provider }}"
          register:                     freeze_fs_results

    - name:                             "Test Execution: Freeze File System on Primary Node init"
      when:                             ansible_hostname == cluster_status_pre.secondary_node
      block:
        - name:                         "Test Execution: CleanUp any failed resource"
          ansible.builtin.command:      "crm_resource --cleanup"
          register:                     cleanup_failed_resource_post
          changed_when:                 cleanup_failed_resource_post.rc == 0
          ignore_errors:                true

        - name:                         "Test Execution: Validate HANA DB cluster status 1"
          when:                         cluster_status_pre.AUTOMATED_REGISTER | lower == "true"
          get_cluster_status_db:
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            ansible_os_family:          "{{ ansible_os_family | upper }}"
          register:                     cluster_status_test_execution
          retries:                      50
          delay:                        10
          until: |
                                        cluster_status_test_execution.primary_node == cluster_status_pre.secondary_node and
                                        cluster_status_test_execution.secondary_node == cluster_status_pre.primary_node

    - name:                             "Test Execution: Freeze File System on Primary Node init"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Validate HANA DB cluster status 2"
          get_cluster_status_db:
            operation_step:             "post_failover"
            database_sid:               "{{ db_sid | lower }}"
            ansible_os_family:          "{{ ansible_os_family | upper }}"
          register:                     cluster_status_post
          retries:                      50
          delay:                        10
          until: |
                                        cluster_status_post.primary_node == cluster_status_pre.secondary_node and
                                        cluster_status_post.secondary_node == cluster_status_pre.primary_node


        - name:                         "Test Execution: Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: |
                                                Old primary: {{ cluster_status_pre.primary_node }}
                                                New primary: {{ cluster_status_post.primary_node }}
                                                Old secondary: {{ cluster_status_pre.secondary_node }}
                                                New secondary: {{ cluster_status_post.secondary_node }}
            test_case_details_from_test_case: {
                                                "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                                "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                                "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                                "Test Execution: Freeze FS results": "{{ freeze_fs_results }}",
                                                "Post Validations: Validate HANA DB cluster status": "{{ cluster_status_post }}",
                                              }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"

- name:                                 "Pre Validations: Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for HANA DB cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                          "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                          "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                          "Cluster Status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
