# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

- name:                                 "Test Setup: {{ item.name | default('') }} - Initialize Test Case"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true
  tags:                                 [pre-validation]

- name:                                 "Pre Validation: {{ item.name | default('') }} - HANA DB Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"
  tags:                                 [pre-validation]

- name:                                 "Test Execution: {{ item.name | default('') }} - Primary Worker Echo B"
  ansible.builtin.include_tasks:        "roles/ha_db_hana/tasks/includes/scaleout-worker-operation.yml"
  tags:                                 [test-execution]
  vars:
    hana_test_target_site_label:        "primary"
    hana_test_target_worker_node:       "{{ primary_worker_nodes | first | default('') }}"
    hana_test_action_command:           "echo b > /proc/sysrq-trigger"
    hana_test_action_async:             1
    hana_test_action_poll:              0
    hana_test_action_ignore_errors:     true
    hana_test_requires_reboot:          true
