# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |               Crash the primary node with echo b                           |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup: {{ item.name | default('') }} - Initialize Test Case"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true
  tags:                                 [pre-validation]

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validation: {{ item.name | default('') }} - HANA DB Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"
  tags:                                 [pre-validation]

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: {{ item.name | default('') }} - Primary Node Crash with echo b init"
  become:                               true
  when:
                                        - node_tier == "hana"
                                        - pre_validations_status == "PASSED"
                                        - cluster_status_pre.stonith_action == "reboot"
  tags:                                 [test-execution]
  block:
    - name:                             "Test Execution: {{ item.name | default('') }} - Crash the primary node with echo b init"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      tags:                             [test-execution]
      block:
        - name:                         "Test Execution: {{ item.name | default('') }} - Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ hostvars[cluster_status_pre.primary_node].ansible_hostname }}"

        - name:                         "Test Execution: {{ item.name | default('') }} - Echo b"
          ansible.builtin.shell:        echo b > /proc/sysrq-trigger
          async:                        1
          poll:                         0
          ignore_errors:                true
          register:                     echo_b_result

    - name:                             "Test Execution: {{ item.name | default('') }} - Switch to secondary node"
      when:                             ansible_hostname == cluster_status_pre.secondary_node
      tags:                             [test-execution]
      block:
        - name:                         "Test Execution: {{ item.name | default('') }} - Validate HANA DB cluster status (failover)"
          when:                         cluster_status_pre.AUTOMATED_REGISTER == "true"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
            hana_topology:                "{{ hana_topology | default('scale_up') }}"
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          register:                     cluster_status_test_execution
          until: >
                                        cluster_status_test_execution.primary_node != "" and
                                        (
                                          (hana_topology | default('scale_up') == 'scale_out_hsr' and
                                           cluster_status_test_execution.primary_node in cluster_status_pre.secondary_site_nodes and
                                           cluster_status_test_execution.primary_node != cluster_status_pre.primary_node and
                                           cluster_status_test_execution.secondary_node != "")
                                          or
                                          (hana_topology | default('scale_up') != 'scale_out_hsr' and
                                           cluster_status_test_execution.primary_node == cluster_status_pre.secondary_node and
                                           cluster_status_test_execution.secondary_node == cluster_status_pre.primary_node)
                                        )

        - name:                         "Test Execution: {{ item.name | default('') }} - Validate HANA DB cluster status"
          when:                         cluster_status_pre.AUTOMATED_REGISTER == "false"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
            hana_topology:                "{{ hana_topology | default('scale_up') }}"
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          register:                     cluster_status_test_execution
          until: >
                                        cluster_status_test_execution.primary_node != "" and
                                        (
                                          (hana_topology | default('scale_up') == 'scale_out_hsr' and
                                           cluster_status_test_execution.primary_node in cluster_status_pre.secondary_site_nodes and
                                           cluster_status_test_execution.secondary_node == "")
                                          or
                                          (hana_topology | default('scale_up') != 'scale_out_hsr' and
                                           cluster_status_test_execution.primary_node == cluster_status_pre.secondary_node and
                                           cluster_status_test_execution.secondary_node == "")
                                        )

    - name:                             "Test Execution: {{ item.name | default('') }} - Switch back to primary node"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      tags:                             [test-execution]
      block:
        - name:                         "Test Execution: {{ item.name | default('') }} - Set facts for the failed resource"
          when:                         cluster_status_pre.AUTOMATED_REGISTER == "false"
          ansible.builtin.set_fact:
            replication_mode:           "{{ cluster_status_pre.replication_mode }}"
            primary_site_name:          "{{ cluster_status_pre.primary_site_name }}"
            operation_mode:             "{{ cluster_status_pre.operation_mode }}"

        - name:                         "Test Execution: {{ item.name | default('') }} - Register the failed resource"
          when:                         cluster_status_pre.AUTOMATED_REGISTER == "false"
          become:                       true
          become_user:                  "{{ db_sid | lower }}adm"
          ansible.builtin.shell: |
                                        source /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number | upper }}/HDBSettings.sh && \
                                        /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe/hdbnsutil -sr_register \
                                        --remoteHost={{ hostvars[cluster_status_pre.secondary_node].cluster_status_test_execution.primary_node }} \
                                        --remoteInstance={{ db_instance_number }} \
                                        --replicationMode={{ replication_mode }} \
                                        --name={{ primary_site_name }} \
                                        --operationMode={{ operation_mode }} --online
          register:                     hana_db_register_failed_resource
          args:
            executable:                 /bin/bash

        - name:                         "Test Execution: {{ item.name | default('') }} - CleanUp any failed resource"
          ansible.builtin.command:      "crm_resource --cleanup"
          register:                     cleanup_failed_resource_post
          changed_when:                 cleanup_failed_resource_post.rc == 0
          ignore_errors:                true

        - name:                         "Test Execution: {{ item.name | default('') }} - Validate HANA DB cluster status (post recovery)"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "post_failover"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
            hana_topology:                "{{ hana_topology | default('scale_up') }}"
          register:                     cluster_status_post
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: >
                                        cluster_status_post.primary_node != "" and
                                        cluster_status_post.secondary_node != "" and
                                        (
                                          (hana_topology | default('scale_up') == 'scale_out_hsr' and
                                           cluster_status_post.primary_node in cluster_status_pre.secondary_site_nodes and
                                           cluster_status_post.primary_node != cluster_status_pre.primary_node)
                                          or
                                          (hana_topology | default('scale_up') != 'scale_out_hsr' and
                                           cluster_status_post.primary_node == cluster_status_pre.secondary_node and
                                           cluster_status_post.secondary_node == cluster_status_pre.primary_node)
                                        ) and
                                        (cluster_status_post.worker_node_scores_valid | default(false))

        - name:                         "Test Execution: {{ item.name | default('') }} - Determine test execution status"
          ansible.builtin.set_fact:
            test_execution_status:      "{{ 'PASSED' if (
                                            (hana_topology | default('scale_up') == 'scale_out_hsr' and
                                             cluster_status_post.primary_node in cluster_status_pre.secondary_site_nodes and
                                             cluster_status_post.primary_node != cluster_status_pre.primary_node)
                                            or
                                            (hana_topology | default('scale_up') != 'scale_out_hsr' and
                                             cluster_status_post.primary_node == cluster_status_pre.secondary_node and
                                             cluster_status_post.secondary_node == cluster_status_pre.primary_node)
                                          ) else 'FAILED' }}"

        - name:                         "Test Execution: {{ item.name | default('') }} - Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Report: {{ item.name | default('') }} - Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: |
                                        Old primary: {{ cluster_status_pre.primary_node }}
                                        New primary: {{ cluster_status_post.primary_node }}
                                        Old secondary: {{ cluster_status_pre.secondary_node }}
                                        New secondary: {{ cluster_status_post.secondary_node }}
            test_case_details_from_test_case: {
                                        "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                        "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                        "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre | default('Not Executed') }}",
                                        "Test Execution: Echo b results": "{{ echo_b_result }}",
                                        "Post Validations: Validate HANA DB cluster status": "{{ cluster_status_post }}",
                                        }

  rescue:
    - name:                             "Rescue: {{ item.name | default('') }} - Handle Failure"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"
      tags:                             [cleanup]

  always:
    - name:                             "Post Validation: {{ item.name | default('') }} - Validate Results"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
      tags:                             [post-validation]

- name:                                 "Pre Validation: {{ item.name | default('') }} - Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Report: {{ item.name | default('') }} - Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for HANA DB cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                          "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                          "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre | default('Not Executed') }}",
                                          "Cluster Status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validation: {{ item.name | default('') }} - Validate Results"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
      tags:                             [post-validation]
