# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

- name:                                 "Pre Validations: HANA DB Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"

- name:                                 "Pre Validations: Check if indexserver process is enabled"
  become:                               true
  check_indexserver:
    database_sid:                       "{{ db_sid | upper }}"
  register:                             index_server_check

- name:                                 "Test Execution: Primary Worker Crash Index"
  when:                                 index_server_check.indexserver_enabled == "yes"
  ansible.builtin.include_tasks:        "roles/ha_db_hana/tasks/includes/scaleout-worker-operation.yml"
  vars:
    hana_test_target_site_label:        "primary"
    hana_test_target_worker_node:       "{{ primary_worker_nodes | first | default('') }}"
    hana_test_action_command:           "killall -9 hdbindexserver"
    hana_test_requires_reboot:          true
