# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

- name:                                 "Test Setup: {{ item.name | default('') }} - Initialize Test Case"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true
  tags:                                 [pre-validation]

- name:                                 "Pre Validation: {{ item.name | default('') }} - HANA DB Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"
  tags:                                 [pre-validation]

- name:                                 "Test Execution: {{ item.name | default('') }} - Secondary Worker Node Kill"
  ansible.builtin.include_tasks:        "roles/ha_db_hana/tasks/includes/scaleout-worker-operation.yml"
  tags:                                 [test-execution]
  when:                                 saphanasr_provider | default('SAPHanaSR') == "SAPHanaSR-angi"
  vars:
    hana_test_target_site_label:        "secondary"
    hana_test_target_worker_node:       "{{ secondary_worker_nodes | first | default('') }}"
    hana_test_action_command:           "/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/HDB kill-9"
    hana_test_action_become_user:       "{{ db_sid | lower }}adm"
